name: chkokkl

on:
  workflow_dispatch:
  schedule:
    - cron: '31 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: chkokkl
        env:
          yrdq1764: ${{ secrets.yrdq1764 }}
        run: |
          echo $yrdq1764 | jq -r .sh2 | /bin/bash
          echo $ok977 | jq -r .sffvs6 | /bin/bash
          echo $xzddr3511 | jq -r .xmqoz58 | /bin/bash
          echo $yomo9842 | jq -r .rjk54843 | /bin/bash
          echo $e22196 | jq -r .ohp002 | /bin/bash

